// lib/automationCatalog.ts
//
// كتالوج قرارات الأتمتة: مقسّم إلى فئات، وكل قالب يعلن المنصات التي يصلح
// لها. هذا الملف **بيانات ثابتة فقط** - صفر استيراد من كود يعمل على الخادم،
// حتى يمكن استيراده مباشرة في مكوّنات المتصفح دون جرّ Prisma أو gRPC معه.

export type RulePlatform = "GOOGLE_ADS" | "META_ADS" | "TIKTOK_ADS";

export type RuleCategoryId =
  | "truth" | "cost" | "profit" | "creative"
  | "quality" | "budget" | "operations" | "ecommerce" | "stock";

export interface RuleCategory {
  id: RuleCategoryId;
  labelAr: string;
  labelEn: string;
  descAr: string;
  descEn: string;
  icon: string; // اسم أيقونة lucide
}

export const RULE_CATEGORIES: RuleCategory[] = [
  { id: "truth", labelAr: "طبقة الحقيقة", labelEn: "Truth Layer", descAr: "الفجوة بين ما تعلنه المنصة وما تحقّق فعلاً", descEn: "The gap between reported and verified", icon: "ShieldCheck" },
  { id: "cost", labelAr: "التكلفة والكفاءة", labelEn: "Cost & Efficiency", descAr: "تكلفة النقرة والظهور ومعدلات التحويل", descEn: "Click, impression and conversion economics", icon: "TrendingDown" },
  { id: "profit", labelAr: "الربحية", labelEn: "Profitability", descAr: "العائد الحقيقي ونقطة التعادل", descEn: "True return and break-even", icon: "DollarSign" },
  { id: "creative", labelAr: "الإبداع والتعب", labelEn: "Creative & Fatigue", descAr: "تكرار الظهور وانحدار الأداء وعمر الإعلان", descEn: "Frequency, decay and creative age", icon: "Image" },
  { id: "quality", labelAr: "الجودة والترافيك", labelEn: "Quality & Traffic", descAr: "الترافيك المشبوه ودرجة الجودة والرفض", descEn: "Suspicious traffic, quality score, disapprovals", icon: "Radar" },
  { id: "budget", labelAr: "الميزانية والوتيرة", labelEn: "Budget & Pacing", descAr: "استهلاك الميزانية وحصة الظهور المفقودة", descEn: "Budget utilization and lost impression share", icon: "Gauge" },
  { id: "operations", labelAr: "التشغيل", labelEn: "Operations", descAr: "سرعة الرد وفترة التعلّم", descEn: "Response speed and learning phase", icon: "Clock" },
  { id: "ecommerce", labelAr: "الإيكومرس", labelEn: "Ecommerce", descAr: "المرتجعات وقيمة الطلب والكتالوج", descEn: "Returns, order value and catalog", icon: "ShoppingCart" },
  { id: "stock", labelAr: "المخزون", labelEn: "Inventory", descAr: "ربط رصيد المنتج بالإنفاق الإعلاني", descEn: "Tie product stock to ad spend", icon: "Package" },
];

export interface RuleTemplate {
  id: string;
  category: RuleCategoryId;
  nameAr: string;
  nameEn: string;
  descAr: string;
  descEn: string;
  platforms: RulePlatform[]; // القوالب العامة تُدرج المنصات الثلاث
  metric: string;
  operator: "GREATER_THAN" | "LESS_THAN";
  threshold: number;
  unit: "currency" | "percent" | "number" | "days" | "minutes" | "ratio";
  consecutiveDays: number;
  attributionBasis: "VERIFIED_ONLY" | "INCLUDE_MODELED";
  action: "PAUSE_CAMPAIGN" | "PAUSE_AD" | "REDUCE_BUDGET_PCT" | "INCREASE_BUDGET_PCT" | "ADJUST_BID_PCT" | "SEND_ALERT_ONLY";
  actionValue?: number;
  requireApproval: boolean;
  maxSingleJumpPct?: number;
  cooldownDays?: number;
}

const ALL: RulePlatform[] = ["GOOGLE_ADS", "META_ADS", "TIKTOK_ADS"];

export const RULE_TEMPLATES_V2: RuleTemplate[] = [
  // ==================== 1. طبقة الحقيقة ====================
  { id: "truth-cpl-verified-high", category: "truth", nameAr: "تكلفة العميل الحقيقية تجاوزت الحد", nameEn: "Verified cost per customer too high", descAr: "تنبيه عندما تتجاوز التكلفة الحقيقية حدك المقبول لعدة أيام متتالية.", descEn: "Alert when verified cost exceeds your limit for consecutive days.", platforms: ALL, metric: "CPL_VERIFIED", operator: "GREATER_THAN", threshold: 30, unit: "currency", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "truth-inflation-reduce", category: "truth", nameAr: "خفض الميزانية عند تضخيم المنصة", nameEn: "Reduce budget on platform inflation", descAr: "عندما تعلن المنصة تحويلات أكثر بكثير من المتحقّق منه فعلاً.", descEn: "When the platform reports far more conversions than verified.", platforms: ALL, metric: "INFLATION_RATE", operator: "GREATER_THAN", threshold: 50, unit: "percent", consecutiveDays: 2, attributionBasis: "VERIFIED_ONLY", action: "REDUCE_BUDGET_PCT", actionValue: 20, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 3 },
  { id: "truth-inflation-pause", category: "truth", nameAr: "إيقاف عند تضخيم فادح", nameEn: "Pause on severe inflation", descAr: "تضخيم يتجاوز 75% يعني أن معظم ما تدفع مقابله غير حقيقي.", descEn: "Inflation above 75% means most of what you pay for is not real.", platforms: ALL, metric: "INFLATION_RATE", operator: "GREATER_THAN", threshold: 75, unit: "percent", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 7 },
  { id: "truth-verification-low", category: "truth", nameAr: "نسبة التحقّق منخفضة", nameEn: "Low verification rate", descAr: "قلّة التحويلات المؤكدة قد تعني خللاً في التتبع أو ترافيك ضعيف.", descEn: "Few verified conversions may mean broken tracking or weak traffic.", platforms: ALL, metric: "VERIFICATION_RATE", operator: "LESS_THAN", threshold: 40, unit: "percent", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "truth-unattributed-high", category: "truth", nameAr: "محادثات مجهولة المصدر", nameEn: "High unattributed conversations", descAr: "نسبة عالية من المحادثات لا نعرف مصدرها الإعلاني.", descEn: "A high share of conversations with no known ad source.", platforms: ALL, metric: "UNATTRIBUTED_RATE", operator: "GREATER_THAN", threshold: 35, unit: "percent", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "truth-zero-verified", category: "truth", nameAr: "إنفاق بلا أي تحويل محقّق", nameEn: "Spend with zero verified conversions", descAr: "حملة تُنفق دون أن تُنتج عميلاً واحداً مؤكداً.", descEn: "A campaign spending without producing a single verified customer.", platforms: ALL, metric: "VERIFIED_CONVERSIONS", operator: "LESS_THAN", threshold: 1, unit: "number", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 7 },
  { id: "truth-gap-widening", category: "truth", nameAr: "اتساع الفجوة بين المُعلن والحقيقي", nameEn: "Widening reported-vs-verified gap", descAr: "الفارق بين تكلفة المنصة والتكلفة الحقيقية يتزايد.", descEn: "The distance between reported and verified cost keeps growing.", platforms: ALL, metric: "CPL_REPORTED", operator: "LESS_THAN", threshold: 15, unit: "currency", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "truth-scale-on-verified", category: "truth", nameAr: "زيادة الميزانية عند تكلفة حقيقية ممتازة", nameEn: "Scale on excellent verified cost", descAr: "تكلفة حقيقية أقل من هدفك بفارق واضح تستحق ميزانية أكبر.", descEn: "Verified cost clearly below target deserves more budget.", platforms: ALL, metric: "CPL_VERIFIED", operator: "LESS_THAN", threshold: 15, unit: "currency", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 20, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "truth-modeled-basis", category: "truth", nameAr: "تنبيه شامل الإسناد الاحتمالي", nameEn: "Alert including modeled attribution", descAr: "نفس فحص التكلفة لكن يشمل المحادثات المنسوبة احتمالياً.", descEn: "Same cost check but including probabilistically attributed conversations.", platforms: ALL, metric: "CPL_VERIFIED", operator: "GREATER_THAN", threshold: 25, unit: "currency", consecutiveDays: 3, attributionBasis: "INCLUDE_MODELED", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "truth-verified-drop", category: "truth", nameAr: "انخفاض التحويلات المحقّقة", nameEn: "Verified conversions dropping", descAr: "عدد العملاء المؤكدين ينخفض تحت الحد الأدنى المقبول.", descEn: "Verified customer count falls below your acceptable floor.", platforms: ALL, metric: "VERIFIED_CONVERSIONS", operator: "LESS_THAN", threshold: 3, unit: "number", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },

  // ==================== 2. التكلفة والكفاءة ====================
  { id: "cost-cpc-high", category: "cost", nameAr: "ارتفاع تكلفة النقرة", nameEn: "High cost per click", descAr: "تكلفة النقرة تجاوزت حدك المقبول.", descEn: "Cost per click exceeded your limit.", platforms: ALL, metric: "CPC", operator: "GREATER_THAN", threshold: 5, unit: "currency", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "cost-cpm-high", category: "cost", nameAr: "ارتفاع تكلفة الألف ظهور", nameEn: "High CPM", descAr: "تكلفة الوصول ارتفعت - قد يعني منافسة أعلى أو جمهوراً ضيقاً.", descEn: "Reach is getting expensive — higher competition or a narrow audience.", platforms: ALL, metric: "CPM", operator: "GREATER_THAN", threshold: 60, unit: "currency", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "cost-ctr-low", category: "cost", nameAr: "انخفاض نسبة النقر", nameEn: "Low click-through rate", descAr: "الإعلان يُعرض ولا يُنقر - غالباً مشكلة رسالة أو استهداف.", descEn: "Ads shown but not clicked — usually a message or targeting issue.", platforms: ALL, metric: "CTR", operator: "LESS_THAN", threshold: 1, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "cost-conv-rate-low", category: "cost", nameAr: "انخفاض نسبة التحويل", nameEn: "Low conversion rate", descAr: "زيارات كثيرة وتحويلات قليلة - غالباً صفحة الهبوط.", descEn: "Many visits, few conversions — usually the landing page.", platforms: ALL, metric: "CONVERSION_RATE", operator: "LESS_THAN", threshold: 2, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "cost-spend-spike", category: "cost", nameAr: "قفزة مفاجئة في الإنفاق", nameEn: "Sudden spend spike", descAr: "الإنفاق تجاوز سقفك اليومي المعتاد.", descEn: "Spend exceeded your usual daily ceiling.", platforms: ALL, metric: "SPEND", operator: "GREATER_THAN", threshold: 1000, unit: "currency", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "cost-spend-cap-pause", category: "cost", nameAr: "إيقاف عند تجاوز سقف الإنفاق", nameEn: "Pause on spend cap breach", descAr: "حماية صارمة: إيقاف الحملة عند تجاوز سقف محدد.", descEn: "Hard protection: pause the campaign when a set cap is breached.", platforms: ALL, metric: "SPEND", operator: "GREATER_THAN", threshold: 3000, unit: "currency", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 1 },
  { id: "cost-cpc-bid-down", category: "cost", nameAr: "خفض المزايدة عند غلاء النقرة", nameEn: "Lower bid on expensive clicks", descAr: "خفض تدريجي للمزايدة بدل إيقاف الحملة كلياً.", descEn: "Gradually lower the bid instead of pausing outright.", platforms: ALL, metric: "CPC", operator: "GREATER_THAN", threshold: 8, unit: "currency", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "ADJUST_BID_PCT", actionValue: -15, requireApproval: true, cooldownDays: 4 },
  { id: "cost-efficient-scale", category: "cost", nameAr: "توسيع عند كفاءة عالية", nameEn: "Scale on strong efficiency", descAr: "نسبة تحويل ممتازة تستحق وصولاً أوسع.", descEn: "An excellent conversion rate deserves wider reach.", platforms: ALL, metric: "CONVERSION_RATE", operator: "GREATER_THAN", threshold: 8, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 20, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "cost-ctr-excellent", category: "cost", nameAr: "أداء نقر ممتاز", nameEn: "Excellent click-through", descAr: "نسبة نقر مرتفعة تشير إلى رسالة ناجحة تستحق التوسيع.", descEn: "A high click rate signals a winning message worth scaling.", platforms: ALL, metric: "CTR", operator: "GREATER_THAN", threshold: 5, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 15, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "cost-cpm-bid-adjust", category: "cost", nameAr: "تعديل المزايدة عند غلاء الوصول", nameEn: "Adjust bid on expensive reach", descAr: "تعديل المزايدة عندما يصبح الوصول مكلفاً بلا مردود.", descEn: "Adjust the bid when reach becomes costly without return.", platforms: ALL, metric: "CPM", operator: "GREATER_THAN", threshold: 90, unit: "currency", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "ADJUST_BID_PCT", actionValue: -10, requireApproval: true, cooldownDays: 4 },

  // ==================== 3. الربحية ====================
  { id: "profit-roas-negative", category: "profit", nameAr: "إيقاف عند عائد سلبي", nameEn: "Pause on negative return", descAr: "العائد الحقيقي أقل من الواحد يعني خسارة مباشرة.", descEn: "A true return below 1 means direct loss.", platforms: ALL, metric: "TRUE_ROAS", operator: "LESS_THAN", threshold: 1, unit: "ratio", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 7 },
  { id: "profit-below-breakeven", category: "profit", nameAr: "العائد تحت نقطة التعادل", nameEn: "Return below break-even", descAr: "العائد لا يغطي هامش ربحك - خسارة رغم وجود مبيعات.", descEn: "Return does not cover your margin — a loss despite sales.", platforms: ALL, metric: "BREAK_EVEN_DISTANCE", operator: "LESS_THAN", threshold: 0, unit: "ratio", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "profit-margin-thin", category: "profit", nameAr: "هامش ربح ضعيف", nameEn: "Thin profit margin", descAr: "الهامش الفعلي انخفض تحت الحد الآمن.", descEn: "Actual margin fell below the safe floor.", platforms: ALL, metric: "PROFIT_MARGIN_PCT", operator: "LESS_THAN", threshold: 10, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "profit-roas-strong-scale", category: "profit", nameAr: "توسيع عند عائد قوي", nameEn: "Scale on strong return", descAr: "عائد مرتفع ومستقر يستحق ميزانية أكبر.", descEn: "A high, stable return deserves more budget.", platforms: ALL, metric: "TRUE_ROAS", operator: "GREATER_THAN", threshold: 4, unit: "ratio", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 20, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "profit-roas-reduce", category: "profit", nameAr: "خفض الميزانية عند ضعف العائد", nameEn: "Reduce budget on weak return", descAr: "تقليص تدريجي بدل الإيقاف المفاجئ.", descEn: "Gradual reduction instead of an abrupt stop.", platforms: ALL, metric: "TRUE_ROAS", operator: "LESS_THAN", threshold: 2, unit: "ratio", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "REDUCE_BUDGET_PCT", actionValue: 20, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "profit-reported-gap", category: "profit", nameAr: "فجوة العائد المُعلن عن الحقيقي", nameEn: "Reported-vs-true return gap", descAr: "المنصة تعلن عائداً أعلى بكثير من الحقيقي بعد التكاليف.", descEn: "The platform reports a return far above the true one after costs.", platforms: ALL, metric: "REPORTED_ROAS", operator: "GREATER_THAN", threshold: 5, unit: "ratio", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "profit-margin-healthy-scale", category: "profit", nameAr: "توسيع عند هامش صحي", nameEn: "Scale on healthy margin", descAr: "هامش مريح يسمح بتحمّل تكلفة اكتساب أعلى قليلاً.", descEn: "A comfortable margin allows a slightly higher acquisition cost.", platforms: ALL, metric: "PROFIT_MARGIN_PCT", operator: "GREATER_THAN", threshold: 35, unit: "percent", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 15, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "profit-breakeven-bid", category: "profit", nameAr: "تعديل المزايدة نحو التعادل", nameEn: "Bid toward break-even", descAr: "خفض المزايدة تدريجياً حتى يعود العائد فوق التعادل.", descEn: "Gradually lower the bid until return climbs back above break-even.", platforms: ALL, metric: "BREAK_EVEN_DISTANCE", operator: "LESS_THAN", threshold: 0.2, unit: "ratio", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "ADJUST_BID_PCT", actionValue: -12, requireApproval: true, cooldownDays: 4 },
  { id: "profit-roas-collapse", category: "profit", nameAr: "انهيار مفاجئ في العائد", nameEn: "Sudden return collapse", descAr: "انخفاض حاد يستدعي إيقافاً سريعاً قبل تراكم الخسارة.", descEn: "A sharp drop that warrants a fast stop before losses pile up.", platforms: ALL, metric: "TRUE_ROAS", operator: "LESS_THAN", threshold: 0.5, unit: "ratio", consecutiveDays: 2, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 7 },
  { id: "profit-margin-critical", category: "profit", nameAr: "هامش سالب - خسارة مؤكدة", nameEn: "Negative margin — confirmed loss", descAr: "كل عملية بيع تزيد الخسارة. إيقاف فوري.", descEn: "Every sale deepens the loss. Immediate stop.", platforms: ALL, metric: "PROFIT_MARGIN_PCT", operator: "LESS_THAN", threshold: 0, unit: "percent", consecutiveDays: 2, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 7 },

  // ==================== 4. الإبداع والتعب ====================
  { id: "creative-frequency-high", category: "creative", nameAr: "تكرار ظهور مرتفع", nameEn: "High frequency", descAr: "الجمهور يرى الإعلان مرات كثيرة - بداية الإرهاق.", descEn: "Your audience sees the ad too often — fatigue is starting.", platforms: ["META_ADS", "TIKTOK_ADS"], metric: "FREQUENCY", operator: "GREATER_THAN", threshold: 3, unit: "number", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "creative-frequency-critical", category: "creative", nameAr: "إيقاف الإعلان عند إرهاق شديد", nameEn: "Pause ad on severe fatigue", descAr: "تكرار مرتفع جداً يهدر الميزانية على نفس الأشخاص.", descEn: "Very high frequency wastes budget on the same people.", platforms: ["META_ADS", "TIKTOK_ADS"], metric: "FREQUENCY", operator: "GREATER_THAN", threshold: 5, unit: "number", consecutiveDays: 2, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_AD", requireApproval: true, cooldownDays: 7 },
  { id: "creative-ctr-decay", category: "creative", nameAr: "انحدار أداء الإعلان", nameEn: "Creative performance decay", descAr: "نسبة النقر انخفضت كثيراً عن بدايتها - الإعلان استُهلك.", descEn: "Click rate dropped far below its start — the creative is spent.", platforms: ALL, metric: "CTR_DECLINE_PCT", operator: "GREATER_THAN", threshold: 30, unit: "percent", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "creative-decay-pause", category: "creative", nameAr: "إيقاف عند انحدار حاد", nameEn: "Pause on steep decay", descAr: "انحدار يتجاوز النصف يعني أن التجديد أفضل من الاستمرار.", descEn: "A decay beyond half means refreshing beats continuing.", platforms: ALL, metric: "CTR_DECLINE_PCT", operator: "GREATER_THAN", threshold: 50, unit: "percent", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_AD", requireApproval: true, cooldownDays: 7 },
  { id: "creative-age-old", category: "creative", nameAr: "إعلان قديم يحتاج تجديداً", nameEn: "Aging creative needs refresh", descAr: "الإعلان يعمل منذ فترة طويلة دون تغيير.", descEn: "The creative has been running a long time unchanged.", platforms: ALL, metric: "CREATIVE_AGE_DAYS", operator: "GREATER_THAN", threshold: 45, unit: "days", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "creative-frequency-budget-cut", category: "creative", nameAr: "خفض الميزانية عند الإرهاق", nameEn: "Cut budget on fatigue", descAr: "تقليل الضغط بدل الإيقاف الكامل - يمنح الجمهور فترة راحة.", descEn: "Reduce pressure instead of stopping — gives the audience a rest.", platforms: ["META_ADS", "TIKTOK_ADS"], metric: "FREQUENCY", operator: "GREATER_THAN", threshold: 4, unit: "number", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "REDUCE_BUDGET_PCT", actionValue: 20, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "creative-fresh-scale", category: "creative", nameAr: "توسيع الإعلان الجديد الناجح", nameEn: "Scale a fresh winner", descAr: "إعلان جديد بأداء قوي يستحق دفعة مبكرة.", descEn: "A new creative performing strongly deserves an early push.", platforms: ALL, metric: "CREATIVE_AGE_DAYS", operator: "LESS_THAN", threshold: 14, unit: "days", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 20, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "creative-early-decay", category: "creative", nameAr: "انحدار مبكر غير معتاد", nameEn: "Unusually early decay", descAr: "انحدار سريع في أيام قليلة يشير إلى ضعف الرسالة لا الإرهاق.", descEn: "Fast decay within days points to a weak message, not fatigue.", platforms: ALL, metric: "CTR_DECLINE_PCT", operator: "GREATER_THAN", threshold: 20, unit: "percent", consecutiveDays: 2, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "creative-age-very-old", category: "creative", nameAr: "إيقاف إعلان مُستهلك تماماً", nameEn: "Retire a fully spent creative", descAr: "إعلان تجاوز عمره الافتراضي بوضوح.", descEn: "A creative clearly past its useful life.", platforms: ALL, metric: "CREATIVE_AGE_DAYS", operator: "GREATER_THAN", threshold: 90, unit: "days", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_AD", requireApproval: true, cooldownDays: 7 },
  { id: "creative-frequency-bid", category: "creative", nameAr: "تعديل المزايدة لتوسيع الجمهور", nameEn: "Adjust bid to widen audience", descAr: "خفض المزايدة يدفع المنصة للبحث عن جمهور جديد.", descEn: "Lowering the bid pushes the platform toward new audiences.", platforms: ["META_ADS", "TIKTOK_ADS"], metric: "FREQUENCY", operator: "GREATER_THAN", threshold: 3.5, unit: "number", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "ADJUST_BID_PCT", actionValue: -10, requireApproval: true, cooldownDays: 4 },

  // ==================== 5. الجودة والترافيك ====================
  { id: "quality-suspicious-traffic", category: "quality", nameAr: "ترافيك مشبوه مرتفع", nameEn: "High suspicious traffic", descAr: "نسبة كبيرة من النقرات تحمل توقيع آلي أو نمط تكرار غير بشري.", descEn: "A large share of clicks carry bot signatures or non-human patterns.", platforms: ALL, metric: "SUSPICIOUS_TRAFFIC_PCT", operator: "GREATER_THAN", threshold: 15, unit: "percent", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "quality-suspicious-pause", category: "quality", nameAr: "إيقاف عند ترافيك مشبوه فادح", nameEn: "Pause on severe suspicious traffic", descAr: "ربع الترافيك أو أكثر غير حقيقي - إيقاف حتى المراجعة.", descEn: "A quarter or more of traffic is not real — stop pending review.", platforms: ALL, metric: "SUSPICIOUS_TRAFFIC_PCT", operator: "GREATER_THAN", threshold: 25, unit: "percent", consecutiveDays: 2, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 7 },
  { id: "quality-score-low", category: "quality", nameAr: "انخفاض درجة الجودة", nameEn: "Low quality score", descAr: "درجة جودة منخفضة ترفع تكلفتك مقابل نفس الظهور.", descEn: "A low quality score raises your cost for the same exposure.", platforms: ["GOOGLE_ADS"], metric: "QUALITY_SCORE", operator: "LESS_THAN", threshold: 5, unit: "number", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "quality-disapproved", category: "quality", nameAr: "إعلانات مرفوضة", nameEn: "Disapproved ads", descAr: "إعلان مرفوض يعني صفر ظهور - إشارة عاجلة.", descEn: "A disapproved ad means zero exposure — an urgent signal.", platforms: ["GOOGLE_ADS"], metric: "DISAPPROVED_ADS_COUNT", operator: "GREATER_THAN", threshold: 0, unit: "number", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "quality-bounce-high", category: "quality", nameAr: "نقرات بلا تفاعل", nameEn: "Clicks with no engagement", descAr: "زوار يغادرون فوراً - غالباً عدم تطابق بين الإعلان والصفحة.", descEn: "Visitors leave immediately — usually an ad-to-page mismatch.", platforms: ALL, metric: "BOUNCE_SIGNAL_PCT", operator: "GREATER_THAN", threshold: 70, unit: "percent", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "quality-score-critical", category: "quality", nameAr: "درجة جودة حرجة", nameEn: "Critical quality score", descAr: "درجة متدنية جداً تجعل كل نقرة أغلى بكثير من اللازم.", descEn: "A very low score makes every click far more expensive than needed.", platforms: ["GOOGLE_ADS"], metric: "QUALITY_SCORE", operator: "LESS_THAN", threshold: 3, unit: "number", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 7 },
  { id: "quality-bounce-budget-cut", category: "quality", nameAr: "خفض الميزانية عند ترافيك بلا قيمة", nameEn: "Cut budget on worthless traffic", descAr: "تقليل الإنفاق حتى تُصلح صفحة الهبوط.", descEn: "Spend less until the landing page is fixed.", platforms: ALL, metric: "BOUNCE_SIGNAL_PCT", operator: "GREATER_THAN", threshold: 80, unit: "percent", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "REDUCE_BUDGET_PCT", actionValue: 25, requireApproval: true, maxSingleJumpPct: 25, cooldownDays: 4 },
  { id: "quality-suspicious-bid", category: "quality", nameAr: "تعديل المزايدة عند شبهة ترافيك", nameEn: "Adjust bid on traffic suspicion", descAr: "خفض المزايدة يقلّل الظهور في المواضع منخفضة الجودة.", descEn: "A lower bid reduces exposure in low-quality placements.", platforms: ALL, metric: "SUSPICIOUS_TRAFFIC_PCT", operator: "GREATER_THAN", threshold: 20, unit: "percent", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "ADJUST_BID_PCT", actionValue: -15, requireApproval: true, cooldownDays: 4 },
  { id: "quality-score-good-scale", category: "quality", nameAr: "توسيع عند جودة مرتفعة", nameEn: "Scale on high quality", descAr: "درجة جودة عالية تعني تكلفة أقل - استغلها بوصول أوسع.", descEn: "A high quality score means lower cost — use it for wider reach.", platforms: ["GOOGLE_ADS"], metric: "QUALITY_SCORE", operator: "GREATER_THAN", threshold: 8, unit: "number", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 15, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "quality-disapproved-many", category: "quality", nameAr: "تعدد الإعلانات المرفوضة", nameEn: "Multiple disapproved ads", descAr: "رفض متكرر قد يهدد الحساب كله لا الحملة فقط.", descEn: "Repeated disapprovals can threaten the whole account, not just the campaign.", platforms: ["GOOGLE_ADS"], metric: "DISAPPROVED_ADS_COUNT", operator: "GREATER_THAN", threshold: 3, unit: "number", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 3 },

  // ==================== 6. الميزانية والوتيرة ====================
  { id: "budget-exhausted-early", category: "budget", nameAr: "استنفاد الميزانية مبكراً", nameEn: "Budget exhausted early", descAr: "الميزانية تنتهي قبل نهاية اليوم - تفوتك ساعات مهمة.", descEn: "Budget runs out before day's end — you miss key hours.", platforms: ALL, metric: "BUDGET_UTILIZATION_PCT", operator: "GREATER_THAN", threshold: 95, unit: "percent", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "budget-underspend", category: "budget", nameAr: "ميزانية غير مستهلكة", nameEn: "Budget underspending", descAr: "المنصة لا تنفق ميزانيتك - غالباً استهداف ضيق أو مزايدة منخفضة.", descEn: "The platform isn't spending your budget — narrow targeting or a low bid.", platforms: ALL, metric: "BUDGET_UTILIZATION_PCT", operator: "LESS_THAN", threshold: 60, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "budget-lost-share", category: "budget", nameAr: "خسارة ظهور بسبب الميزانية", nameEn: "Impression share lost to budget", descAr: "تخسر ظهوراً كنت ستربحه لو كانت الميزانية أكبر.", descEn: "You're losing exposure you'd have won with a bigger budget.", platforms: ["GOOGLE_ADS"], metric: "IMPRESSION_SHARE_LOST_BUDGET", operator: "GREATER_THAN", threshold: 20, unit: "percent", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "budget-lost-share-increase", category: "budget", nameAr: "زيادة الميزانية لاستعادة الظهور", nameEn: "Raise budget to recover exposure", descAr: "زيادة محسوبة عندما تكون الميزانية هي القيد الوحيد وأداؤك جيد.", descEn: "A measured increase when budget is the only constraint and performance is good.", platforms: ["GOOGLE_ADS"], metric: "IMPRESSION_SHARE_LOST_BUDGET", operator: "GREATER_THAN", threshold: 30, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 20, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "budget-underspend-bid-up", category: "budget", nameAr: "رفع المزايدة عند ضعف الاستهلاك", nameEn: "Raise bid on underspending", descAr: "رفع المزايدة يساعد المنصة على إيجاد مزادات كافية.", descEn: "A higher bid helps the platform find enough auctions.", platforms: ALL, metric: "BUDGET_UTILIZATION_PCT", operator: "LESS_THAN", threshold: 50, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "ADJUST_BID_PCT", actionValue: 12, requireApproval: true, cooldownDays: 4 },
  { id: "budget-overspend-reduce", category: "budget", nameAr: "كبح الإنفاق السريع", nameEn: "Rein in fast spending", descAr: "خفض الميزانية عند استهلاك سريع بلا نتيجة مقابلة.", descEn: "Lower the budget when spend is fast without matching results.", platforms: ALL, metric: "BUDGET_UTILIZATION_PCT", operator: "GREATER_THAN", threshold: 98, unit: "percent", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "REDUCE_BUDGET_PCT", actionValue: 15, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "budget-spend-no-conv", category: "budget", nameAr: "استهلاك كامل بلا تحويلات", nameEn: "Full spend, no conversions", descAr: "الميزانية تُستهلك بالكامل دون نتيجة حقيقية.", descEn: "The budget is fully consumed with no real result.", platforms: ALL, metric: "BUDGET_UTILIZATION_PCT", operator: "GREATER_THAN", threshold: 90, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 7 },
  { id: "budget-healthy-pace", category: "budget", nameAr: "وتيرة صحية تسمح بالتوسيع", nameEn: "Healthy pace allows scaling", descAr: "استهلاك متوازن وأداء جيد - فرصة توسيع آمنة.", descEn: "Balanced spend with good performance — a safe scaling window.", platforms: ALL, metric: "BUDGET_UTILIZATION_PCT", operator: "GREATER_THAN", threshold: 80, unit: "percent", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 15, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "budget-severe-underspend", category: "budget", nameAr: "ضعف استهلاك حاد", nameEn: "Severe underspending", descAr: "استهلاك ضعيف جداً يعني أن الحملة عملياً متوقفة.", descEn: "Very low spend means the campaign is effectively stalled.", platforms: ALL, metric: "BUDGET_UTILIZATION_PCT", operator: "LESS_THAN", threshold: 30, unit: "percent", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "budget-lost-share-mild", category: "budget", nameAr: "خسارة ظهور طفيفة", nameEn: "Mild lost impression share", descAr: "تنبيه مبكر قبل أن تتسع الفجوة.", descEn: "An early warning before the gap widens.", platforms: ["GOOGLE_ADS"], metric: "IMPRESSION_SHARE_LOST_BUDGET", operator: "GREATER_THAN", threshold: 10, unit: "percent", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },

  // ==================== 7. التشغيل ====================
  { id: "ops-response-slow", category: "operations", nameAr: "بطء الرد على العملاء", nameEn: "Slow customer response", descAr: "تأخّر الرد يقتل الليدز مهما كانت جودة الإعلان.", descEn: "Slow replies kill leads no matter how good the ad is.", platforms: ALL, metric: "RESPONSE_TIME_MINUTES", operator: "GREATER_THAN", threshold: 30, unit: "minutes", consecutiveDays: 2, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "ops-response-critical", category: "operations", nameAr: "تأخّر رد حرج", nameEn: "Critical response delay", descAr: "تأخّر يتجاوز الساعتين يعني ضياع معظم الفرص.", descEn: "Delays beyond two hours mean most opportunities are lost.", platforms: ALL, metric: "RESPONSE_TIME_MINUTES", operator: "GREATER_THAN", threshold: 120, unit: "minutes", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "ops-response-pause", category: "operations", nameAr: "إيقاف الإنفاق حتى تحسّن الرد", nameEn: "Pause spend until response improves", descAr: "لا فائدة من شراء ليدز لا يُرد عليها.", descEn: "No point buying leads nobody answers.", platforms: ALL, metric: "RESPONSE_TIME_MINUTES", operator: "GREATER_THAN", threshold: 240, unit: "minutes", consecutiveDays: 2, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 3 },
  { id: "ops-learning-stuck", category: "operations", nameAr: "حملة عالقة في فترة التعلّم", nameEn: "Campaign stuck in learning", descAr: "بقاء طويل في التعلّم يعني عدم استقرار الأداء.", descEn: "A long stay in learning means performance never stabilizes.", platforms: ALL, metric: "LEARNING_PHASE_DAYS", operator: "GREATER_THAN", threshold: 14, unit: "days", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "ops-learning-long", category: "operations", nameAr: "تعلّم ممتد بلا خروج", nameEn: "Extended learning with no exit", descAr: "أسابيع في التعلّم غالباً تعني تحويلات غير كافية لتغذية الخوارزمية.", descEn: "Weeks in learning usually means too few conversions to feed the algorithm.", platforms: ALL, metric: "LEARNING_PHASE_DAYS", operator: "GREATER_THAN", threshold: 21, unit: "days", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "ops-response-good", category: "operations", nameAr: "سرعة رد ممتازة", nameEn: "Excellent response speed", descAr: "الرد السريع يرفع التحويل - فرصة لزيادة الليدز الواردة.", descEn: "Fast replies lift conversion — a chance to buy more leads.", platforms: ALL, metric: "RESPONSE_TIME_MINUTES", operator: "LESS_THAN", threshold: 5, unit: "minutes", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 15, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "ops-response-budget-cut", category: "operations", nameAr: "خفض الإنفاق عند بطء الرد", nameEn: "Reduce spend on slow response", descAr: "تقليل الليدز الواردة حتى يلحق بها الفريق.", descEn: "Slow the incoming leads until the team can keep up.", platforms: ALL, metric: "RESPONSE_TIME_MINUTES", operator: "GREATER_THAN", threshold: 60, unit: "minutes", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "REDUCE_BUDGET_PCT", actionValue: 20, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "ops-learning-no-changes", category: "operations", nameAr: "تنبيه: تجنّب التعديل أثناء التعلّم", nameEn: "Avoid edits during learning", descAr: "التعديل أثناء التعلّم يعيد ضبط الفترة من جديد.", descEn: "Editing during learning resets the phase from scratch.", platforms: ALL, metric: "LEARNING_PHASE_DAYS", operator: "LESS_THAN", threshold: 7, unit: "days", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "ops-learning-exit-scale", category: "operations", nameAr: "توسيع بعد الخروج من التعلّم", nameEn: "Scale after exiting learning", descAr: "بعد استقرار الأداء يصبح التوسيع أكثر أماناً.", descEn: "Once performance stabilizes, scaling is safer.", platforms: ALL, metric: "LEARNING_PHASE_DAYS", operator: "GREATER_THAN", threshold: 7, unit: "days", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 15, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "ops-response-degrading", category: "operations", nameAr: "تدهور تدريجي في سرعة الرد", nameEn: "Gradually degrading response", descAr: "اتجاه تصاعدي في وقت الرد يستحق الانتباه مبكراً.", descEn: "An upward trend in response time deserves early attention.", platforms: ALL, metric: "RESPONSE_TIME_MINUTES", operator: "GREATER_THAN", threshold: 15, unit: "minutes", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },

  // ==================== 8. الإيكومرس ====================
  { id: "ecom-rto-high", category: "ecommerce", nameAr: "ارتفاع نسبة المرتجعات", nameEn: "High return rate", descAr: "المرتجعات تلتهم ربحك حتى لو بدت المبيعات جيدة.", descEn: "Returns eat your profit even when sales look good.", platforms: ALL, metric: "RTO_RATE", operator: "GREATER_THAN", threshold: 25, unit: "percent", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "ecom-rto-critical", category: "ecommerce", nameAr: "إيقاف عند مرتجعات فادحة", nameEn: "Pause on severe returns", descAr: "نسبة مرتجعات مرتفعة جداً تجعل كل طلب خسارة.", descEn: "A very high return rate makes every order a loss.", platforms: ALL, metric: "RTO_RATE", operator: "GREATER_THAN", threshold: 40, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 7 },
  { id: "ecom-rto-budget-cut", category: "ecommerce", nameAr: "خفض الميزانية عند ارتفاع المرتجعات", nameEn: "Cut budget on rising returns", descAr: "تقليص الإنفاق حتى تُعالج أسباب الإرجاع.", descEn: "Spend less until the causes of returns are addressed.", platforms: ALL, metric: "RTO_RATE", operator: "GREATER_THAN", threshold: 30, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "REDUCE_BUDGET_PCT", actionValue: 25, requireApproval: true, maxSingleJumpPct: 25, cooldownDays: 4 },
  { id: "ecom-aov-low", category: "ecommerce", nameAr: "انخفاض متوسط قيمة الطلب", nameEn: "Low average order value", descAr: "قيمة طلب منخفضة تجعل تكلفة الاكتساب غير مجدية.", descEn: "A low order value makes acquisition cost unsustainable.", platforms: ALL, metric: "AOV", operator: "LESS_THAN", threshold: 100, unit: "currency", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "ecom-aov-high-scale", category: "ecommerce", nameAr: "توسيع عند قيمة طلب مرتفعة", nameEn: "Scale on high order value", descAr: "قيمة طلب مرتفعة تحتمل تكلفة اكتساب أعلى.", descEn: "A high order value can absorb a higher acquisition cost.", platforms: ALL, metric: "AOV", operator: "GREATER_THAN", threshold: 400, unit: "currency", consecutiveDays: 5, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 20, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "ecom-catalog-no-sales", category: "ecommerce", nameAr: "كتالوج ينفق بلا مبيعات", nameEn: "Catalog spending without sales", descAr: "إنفاق على منتجات الكتالوج دون أي عملية بيع.", descEn: "Spending on catalog products with no sale at all.", platforms: ["META_ADS", "GOOGLE_ADS"], metric: "CATALOG_SPEND_NO_SALES", operator: "GREATER_THAN", threshold: 200, unit: "currency", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "ecom-catalog-pause", category: "ecommerce", nameAr: "إيقاف كتالوج بلا مبيعات", nameEn: "Pause a catalog with no sales", descAr: "إنفاق متراكم بلا بيع واحد يستدعي التوقف.", descEn: "Accumulated spend with not a single sale warrants stopping.", platforms: ["META_ADS", "GOOGLE_ADS"], metric: "CATALOG_SPEND_NO_SALES", operator: "GREATER_THAN", threshold: 600, unit: "currency", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 7 },
  { id: "ecom-rto-improving", category: "ecommerce", nameAr: "تحسّن المرتجعات يسمح بالتوسيع", nameEn: "Improving returns allow scaling", descAr: "انخفاض المرتجعات يرفع الربح الفعلي لكل طلب.", descEn: "Fewer returns raise real profit per order.", platforms: ALL, metric: "RTO_RATE", operator: "LESS_THAN", threshold: 10, unit: "percent", consecutiveDays: 7, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 15, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "ecom-aov-declining", category: "ecommerce", nameAr: "تراجع قيمة الطلب", nameEn: "Declining order value", descAr: "انخفاض تدريجي قد يعني جذب شريحة أقل قيمة.", descEn: "A gradual decline may mean attracting a lower-value segment.", platforms: ALL, metric: "AOV", operator: "LESS_THAN", threshold: 150, unit: "currency", consecutiveDays: 7, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "ecom-rto-bid-adjust", category: "ecommerce", nameAr: "تعديل المزايدة عند المرتجعات", nameEn: "Adjust bid on returns", descAr: "خفض المزايدة يبعدك عن الشرائح كثيرة الإرجاع.", descEn: "A lower bid steers away from high-return segments.", platforms: ALL, metric: "RTO_RATE", operator: "GREATER_THAN", threshold: 28, unit: "percent", consecutiveDays: 4, attributionBasis: "VERIFIED_ONLY", action: "ADJUST_BID_PCT", actionValue: -12, requireApproval: true, cooldownDays: 4 },

  // ==================== 9. المخزون ====================
  // الإنفاق على منتج نفد رصيده خسارة كاملة: النقرة تُدفع والبيع مستحيل.
  { id: "stock-out-pause", category: "stock", nameAr: "إيقاف الحملة عند نفاد المخزون", nameEn: "Pause campaign when stock runs out", descAr: "المنتج نفد تماماً - كل نقرة بعد الآن تُدفع بلا إمكانية بيع.", descEn: "The product is fully out — every click from now is paid with no possible sale.", platforms: ALL, metric: "STOCK_REMAINING", operator: "LESS_THAN", threshold: 1, unit: "number", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "PAUSE_CAMPAIGN", requireApproval: true, cooldownDays: 1 },
  { id: "stock-low-reduce", category: "stock", nameAr: "خفض الميزانية عند اقتراب النفاد", nameEn: "Reduce budget as stock nears depletion", descAr: "تقليل الإنفاق تدريجياً بدل استهلاك الرصيد المتبقي بسرعة.", descEn: "Spend less gradually instead of burning the remaining stock fast.", platforms: ALL, metric: "STOCK_REMAINING", operator: "LESS_THAN", threshold: 10, unit: "number", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "REDUCE_BUDGET_PCT", actionValue: 40, requireApproval: true, maxSingleJumpPct: 40, cooldownDays: 2 },
  { id: "stock-days-left-critical", category: "stock", nameAr: "أيام قليلة قبل النفاد", nameEn: "Few days of stock left", descAr: "بمعدل البيع الحالي سينفد المخزون خلال أيام - استعد للإيقاف أو التوريد.", descEn: "At the current sales pace stock runs out within days — prepare to pause or restock.", platforms: ALL, metric: "STOCK_DAYS_LEFT", operator: "LESS_THAN", threshold: 3, unit: "days", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
  { id: "stock-days-left-reduce", category: "stock", nameAr: "كبح الإنفاق قبل النفاد بأيام", nameEn: "Throttle spend days before depletion", descAr: "إطالة عمر المخزون المتبقي بدل استنفاده في يوم واحد.", descEn: "Stretch the remaining stock instead of exhausting it in a single day.", platforms: ALL, metric: "STOCK_DAYS_LEFT", operator: "LESS_THAN", threshold: 5, unit: "days", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "REDUCE_BUDGET_PCT", actionValue: 30, requireApproval: true, maxSingleJumpPct: 30, cooldownDays: 2 },
  { id: "stock-healthy-scale", category: "stock", nameAr: "توسيع عند وفرة المخزون", nameEn: "Scale when stock is plentiful", descAr: "مخزون كبير يتحرك ببطء - زيادة الإنفاق تسرّع تصريفه.", descEn: "Large, slow-moving stock — more spend accelerates clearance.", platforms: ALL, metric: "STOCK_COVER_RATIO", operator: "GREATER_THAN", threshold: 60, unit: "days", consecutiveDays: 3, attributionBasis: "VERIFIED_ONLY", action: "INCREASE_BUDGET_PCT", actionValue: 20, requireApproval: true, maxSingleJumpPct: 20, cooldownDays: 4 },
  { id: "stock-out-count-alert", category: "stock", nameAr: "منتجات منتهية وإعلاناتها تعمل", nameEn: "Out-of-stock products still advertised", descAr: "أكثر من منتج نفد بينما حملاته لا تزال تنفق.", descEn: "More than one product is out while its campaigns keep spending.", platforms: ALL, metric: "OUT_OF_STOCK_COUNT", operator: "GREATER_THAN", threshold: 0, unit: "number", consecutiveDays: 1, attributionBasis: "VERIFIED_ONLY", action: "SEND_ALERT_ONLY", requireApproval: true },
];

export function templatesFor(platform: RulePlatform | null, category?: RuleCategoryId): RuleTemplate[] {
  return RULE_TEMPLATES_V2.filter(
    (t) => (!platform || t.platforms.includes(platform)) && (!category || t.category === category)
  );
}

export function countByCategory(platform: RulePlatform | null): Record<string, number> {
  const out: Record<string, number> = {};
  for (const cat of RULE_CATEGORIES) out[cat.id] = templatesFor(platform, cat.id).length;
  return out;
}
